DROP TABLE SOLARNODE.LOXONE_CATEGORY;
DROP TABLE SOLARNODE.LOXONE_CONTROL_STATE;
DROP TABLE SOLARNODE.LOXONE_CONTROL;
DROP TABLE SOLARNODE.LOXONE_DATUMSET;
DROP TABLE SOLARNODE.LOXONE_PROPSET;
DROP TABLE SOLARNODE.LOXONE_ROOM;
DROP TABLE SOLARNODE.LOXONE_VEVENT;
DELETE FROM SOLARNODE.SN_SETTINGS WHERE skey LIKE 'loxone%';
DELETE FROM SOLARNODE.SN_SETTINGS WHERE skey LIKE 'solarnode.loxone_%';
